title: "Sandslate Portfolio"
tagline: "A minimal jekyll theme"
description: "This is a preview of the Sandslate, a minimal portfolio theme for jekyll sites"
author: Tareq El Dandachi
github_username: tareqdandachi
baseurl: "/sandslate"
url: "https://tareqdandachi.github.io"

social:
  name: Tareq El Dandachi
  links:
    - https://twitter.com/tareqdandachi
    - https://www.facebook.com/tdandachi
    - https://github.com/tareqdandachi
    - https://www.linkedin.com/in/tareq-el-dandachi-940090173/
    - https://tareqdandachi.github.io

image: https://images.unsplash.com/photo-1573743338941-39db12ef9b64?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1951&q=80

defaults:
  - scope:
      path: ""
    values:
      image: https://images.unsplash.com/photo-1573743338941-39db12ef9b64?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1951&q=80

lang: en_US

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - preview.md
  - read_me.md
  - examples.md

color_mode: light #dark or light theme
right_aligned: false #true or false -> right aligned content or left aligned content

logo_font: 'Allison Script'
title_font: 'Dancing Script'
content_font: 'Hind'

font_link_source: 'https://fonts.googleapis.com/css?family=Dancing+Script:400,700|Hind:300,500,600&display=swap'

defaults:
  -
    scope:
      path: "" # all files in the project
      type: "pages"
    values:
      layout: "page"

extra_meta: <link rel="apple-touch-icon" sizes="180x180" href="assets/favicons/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="32x32" href="assets/favicons/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="assets/favicons/favicon-16x16.png"><link rel="manifest" href="assets/favicons/site.webmanifest"><meta property="og:image" content="https://images.unsplash.com/photo-1573743338941-39db12ef9b64?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1951&q=80" />
