title: "Sandslate Portfolio"
description: "This is a preview of the Sandslate, a minimal portfolio theme for jekyll sites"
github_username: tareqdandachi
baseurl: "/sandslate"
url: "tareqdandachi.github.io"

plugins:
  - jemoji

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - preview.md
  - read_me.md
  - examples.md

color_mode: light #dark or light theme
right_aligned: false #true or false -> right aligned content or left aligned content

logo_font: 'Allison Script'
title_font: 'Dancing Script'
content_font: 'Hind'

font_link_source: 'https://fonts.googleapis.com/css?family=Dancing+Script:400,700|Hind:300,500,600&display=swap'

defaults:
  -
    scope:
      path: "" # all files in the project
      type: "pages"
    values:
      layout: "page"
